#74disagg
tesera/pygypsy pull request #91
Opened 2017-01-31 17:11 UTC by juliannosambatti

2017-01-31 18:01 UTC, jo-tham requested changes
Hey @juliannosambatti here's my review - i might have misunderstood some of the implementation; let me know if that's the case.

The main thing with respect to the correctness
 - i think it should be:

`disaggregatred_var_species = gypsy_var_species * proportion_data_species / proportion_gypsy_species`

note the swap of `*` with `/`

this is described in more detail in one of the comments

i also suggest to take the time to make sure everything is named well, this is a bit tricky because the items in question are hard to distinguish, but it's worth the time! a couple of the comments below relate to this (e.g. PER vs proportion)

2017-01-31 18:01 UTC, jo-tham commented on pygypsy/disagg.py
> +# -*- coding: utf-8 -*-
Lets remove this file from the history since it was changed to disaggregate.py

2017-01-31 18:01 UTC, jo-tham commented on pygypsy/disaggregate.py
> +original_file = pd.read_csv('/Users/juliannosambatti/Documents/Projects/gypsy/10-plots.csv')
i think we should avoid read data into global variables in a module here

do this in the unit test

also, those data are only on your local computer - can you subset them to one or two pertinent plots for the unit test and put them under `data/` here https://github.com/tesera/pygypsy/tree/dev/data

2017-01-31 18:01 UTC, jo-tham commented on pygypsy/disaggregate.py
> +        df['SC_%s' %(data_s)] = df['SC_%s' %  (gypsy_s)] * df['PER_%s_data' % data_s] * df['prop_%s_class' %gypsy_s]
Why did you hoist these (SC and N_bh_--T) into the outer loop? it's a bit confusing to see a different approach for these variables than for the others

2017-01-31 18:01 UTC, jo-tham commented on pygypsy/disaggregate.py
> +    total_prop = {'PER_Aw_data':0, 'PER_Pb_data':0, 'PER_Sw_data':0, 'PER_Fb_data':0, 'PER_Fd_data':0}
i think these would be more accurately called

`prop_--_data`

and

```
for sp, prop in perc_sp:
```

would be more accuratley called

```
for sp, perc in perc_sp:
```

2017-01-31 18:01 UTC, jo-tham commented on pygypsy/disaggregate.py
> +            df['%s_%s' %(v, data_s)] = df['%s_%s' % (v, gypsy_s)] * df['PER_%s_data' % data_s] * df['prop_%s_class' %gypsy_s]
so we have 

new = gypsy * percent_species_in_data * proportion_gypsy_class

an example consider a plot with fd 10% and Sw 40% and Aw 50%

For gypsy, Sw is 50%
Fd is 20% of Sw

fd_density = gypsy_sw_density * percent_fd_data * proportion_fd_class
sw_density = gypsy_sw_density * percent_sw_data * proportion_sw_class

----------------------------

one thing that comes to mind here, is it really percent and proportion? if so i would expect

fd_density = 13.4 * 10 * .5

which is not correct. so mind the naming of the variables

-----------------------

an example consider a plot with fd 10% and Sw 40% and Aw 50%

fd_density = gypsy_sw_density * prop_fd_data * prop_sw_class
fd_density = 13.4 * .1 * .5

sw_density = gypsy_sw_density * prop_sw_data * prop_sw_class
sw_density = 13.4 * .4 * .5

-------------------------------------

that doesn't quite look right to me; am i missing something @juliannosambatti ?

if i'm not missing something, i think it should be 

fd_density = gypsy_sw_density * prop_fd_data / prop_sw_class
fd_density = 13.4 * .2

sw_density = gypsy_sw_density * prop_sw_data / prop_sw_class
sw_density = 13.4 * .8

2017-01-31 18:01 UTC, jo-tham commented on tests/test_disagg.py
> +
the best way to prove the routine works is to add a test here for the `build_disaggregated_simulated_df` function; you can use the forward simulation comparison tests or the data prep tests for reference - need to do that before merging this into dev anyway.

2017-01-31 18:06 UTC, jo-tham commented
@juliannosambatti a couple other things:

please fixup the tests which aren't passing; i can help if you're not sure how to resolve it - best thing to do is just post a comment on this pull request with an example of the test output indicating why its not passing if you get stuck

------------------------

for future reference please keep commit messages brief, ~50 characters

There is a tesera standard for this borrowed from the git community:
https://github.com/tesera/knowledge/wiki/One-Convention#the-seven-rules-of-a-great-git-commit-message

if you have more details to add and you are using the CLI you can use

```
git commit -m 'this is the summary of what was done

here are more detailed
stuff about the commit
and such'
```

2017-01-31 18:06 UTC, juliannosambatti commented
You are right up there. The main problem is to avoid a division by zero when proportion of gypsy speceis is zero.

2017-01-31 18:09 UTC, jo-tham commented
@juliannosambatti use this

``` python
try:
    # the division
except ZeroDivisionError:
    # what to do if the gypsy species is 0; probably just assign the variable to 0
```

2017-01-31 18:18 UTC, juliannosambatti commented
Actually this is wrong too. The class proportion is the sum of component proportion. Thus we just need to multiply by the original proportion to get the species variable

2017-01-31 18:26 UTC, jo-tham commented
> Actually this is wrong too. The class proportion is the sum of component proportion. Thus we just need to multiply by the original proportion to get the species variable

@juliannosambatti can you make an example in comment here?

2017-02-01 00:11 UTC, jo-tham approved these changes

2017-02-01 00:40 UTC, merged